pyrad/client.py: add patch for pyrad.Client to use poll() instead of select()
Under heavy load the 1024-descriptor limit of select() could lead to
ValueError: filedescriptor out of range in select()

References: jira SCB-9464
References: azure #336751